os:
  - linux
  - osx
  - windows
env:
  - TARGET=noui
  - TARGET=noui_c
  - TARGET=noframes
matrix:
  exclude:
    - os: windows
      env: TARGET=noui_c
    - os: windows
      env: TARGET=nouiframes
language: cpp
script: ./travis/build
