#!/bin/bash
echo "hellow"
if [[ "$TRAVIS_OS_NAME" = "windows" ]] ; then
	set
	dir "c:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Tools\\"
else
	set -ev
	pushd demo/noui && make clean && make && popd
	pushd demo/noui_c && make clean && make && popd
	pushd demo/noframes && make clean && make && popd
fi
