#!/bin/bash
echo "hellow"
echo "$TARGET"
if [[ "$TRAVIS_OS_NAME" = "windows" ]] ; then
	export PATH="c:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\Bin\\":$PATH
	echo pushd demo/$TARGET
	cd
	dir
	cd demo
	cd $TARGET
	cd
	dir
	MSBuild.exe /property:Configuration="Release";Platform="x64"
	MSBuild.exe /property:Configuration="Debug";Platform="x64"
	popd
else
	echo $TARGET
	pushd demo/$TARGET
	pwd
	make clean 
	make 
	popd
fi
